

name: Despliegue automático a Surge.sh

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Desplegar en Surge.sh
    steps:
      - uses: actions/checkout@v2
      
      - name: Instalar Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Instalar Surge
        run: npm install -g surge
      
      - name: Desplegar en Surge.sh
        run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}